import SimpleITK as sitk
import numpy as np
from vesseltrackhfm.vesseltrackhfm import VesselTrackHFM
from dataset_creation.extract_roi import LiverImageCreator
import datetime

LAMBDA = 1e4
p = 1.0

IMAGE_DIR = '/home/ishaan/Desktop/UMC_Data/Data/29/20150518'

# Read the DCE MR series
liver_image_obj = LiverImageCreator(raw_data_dir=IMAGE_DIR,
                                    out_size=256)

dce_img, _, lesion_mask = liver_image_obj.apply_liver_mask()


dce_img_np = sitk.GetArrayFromImage(dce_img).transpose((2, 3, 1, 0))
dce_post_contrast_arr = dce_img_np[:, :, :, 10]
dce_pre_contrast_arr = dce_img_np[:, :, :, 0]


# Create subtraction image between post- and pre-contrast phases that highlight the vessels
subtraction_image = np.subtract(dce_post_contrast_arr, dce_pre_contrast_arr)
subtraction_image = np.where(subtraction_image < 0, 0, subtraction_image)

# Save the subtraction image
subtraction_img = sitk.GetImageFromArray(arr=subtraction_image.transpose((2, 0, 1)))
subtraction_img.CopyInformation(lesion_mask)


vessel_tracker = VesselTrackHFM(lmbda=LAMBDA,
                                p=p,
                                sigmas=(0.3, 3, 0.3),
                                alpha=0.5,
                                beta=0.5,
                                gamma=15
                                )

# Test Riemannian metric tensor computation
t1 = datetime.datetime.now()
frangi_response = vessel_tracker.create_riemannian_metric_tensor(image=subtraction_image)
t2 = datetime.datetime.now()
t_exec = (t2-t1).total_seconds()

frangi_response = 1 + LAMBDA*np.power(frangi_response, p)
print('Reimannian metric tensor creation takes {} seconds'.format(t_exec))
frangi_img = sitk.GetImageFromArray(arr=frangi_response.transpose((2, 0, 1)))
frangi_img.CopyInformation(lesion_mask)
sitk.WriteImage(frangi_img, 'frangi_test.nii')

# Compare vesselness image generated by scipy frangi filter
vesselness, distance_map = vessel_tracker(image=subtraction_image)


# Save the outputs using the un-modified code
vesselness_img = sitk.GetImageFromArray(arr=vesselness.transpose((2, 0, 1)))
vesselness_img.CopyInformation(lesion_mask)

distance_map_img = sitk.GetImageFromArray(arr=distance_map.transpose((2, 0, 1)))
distance_map_img.CopyInformation(lesion_mask)

sitk.WriteImage(vesselness_img, 'vesselness_compare.nii')
sitk.WriteImage(distance_map_img, 'distancemap_compare.nii')


